### ISSUE TITLE
하객 입장 플로우 기능 구현

### ISSUE THREAD

**Issue by zzzjinwook** [festal-kestrel/wedding-book-keeper-be#10]
## Feature Description
- 메인페이지를 통해 진입한 하객 입장 플로우의 기능 구현

## Todo list

- [ ] qr인식 기능 및 화면 추가
- [ ] 신랑, 신부 측 선택 및 관계 입력
- [ ] 축의금 금액 입력 화면
- [ ] 입력 받은 정보 db에 저장
- [ ] 완료 후 메인 화면 이동
