### ISSUE TITLE
신랑신부 측 결혼식 생성 구현

### ISSUE THREAD

**Issue by sa46lll** [festal-kestrel/wedding-book-keeper-be#11]
## Feature Description
- 신랑신부 측 결혼식 생성 구현

## Todo list

- [ ] 결혼식 정보 입력
- [ ] QR 코드 발급
- [ ] S3 이미지 저장
- [ ] 이미지 url 업데이트
